name: GH Actions Cron Schedule
on:
  schedule:
    - cron:  '*/20 * * * *'
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 1to10
        run: wget https://lia.liara.run/download/5GB.bin
