name: GH Actions Cron Schedule
on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 1to10
        run: |
          wget https://lia2.liara.run/download/2GB.bin 
          wget https://upn.liara.run/download/2GB.bin
  
